CREATE TABLE appInfo(appInfoId INTEGER PRIMARY KEY AUTOINCREMENT,appInfoName TEXT NOT NULL DEFAULT "",appInfoVersion TEXT NOT NULL DEFAULT 0,appInfoSchemaVersion INTEGER NOT NULL DEFAULT 0,appInfoLastUpdate DATETIME DEFAULT CURRENT_TIMESTAMP,appInfoFirstLaunch INTEGER NOT NULL DEFAULT 0,appInfoTheme INTEGER NOT NULL DEFAULT 0,appInfoInstallDate DATETIME DEFAULT CURRENT_TIMESTAMP,appErrorStamp DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE appErrors(appErrorId INTEGER PRIMARY KEY AUTOINCREMENT,appErrorCode TEXT NOT NULL,appErrorType INTEGER NOT NULL,appErrorText TEXT NOT NULL,appErrorStamp DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_appErrorType ON appErrors(appErrorType);
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("IO_FILE_NOT_FOUND",4,"We couldn't find the requested file. It may have been moved, renamed, or deleted.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("IO_PERMISSION_DENIED",2,"Access denied. Please check your system permissions to ensure PoseStudio can read and write to this folder.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("IO_CORRUPT_ASSET",2,"This 3D asset or project file appears to be corrupted and cannot be loaded properly.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("IO_DISK_FULL",1,"Your computer's storage is full. Please free up some space to save your project and prevent data loss.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("GFX_HARDWARE_UNSUPPORTED",1,"Your graphics card doesn't support the features required to render this 3D scene. Try updating your drivers or checking the hardware requirements.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("GFX_OUT_OF_VRAM",1,"The current scene is too large for your graphics card's video memory. Try hiding complex meshes or reducing texture sizes to prevent a crash.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("GFX_SHADER_ERROR",2,"A visual rendering error occurred. Restarting the application or updating your graphics drivers might resolve this.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("GFX_CONTEXT_LOST",4,"The graphics connection was interrupted. We are attempting to recover the scene, but you may need to restart the application.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("DB_CONNECTION_FAILED",1,"PoseStudio couldn't access its local data files. Restarting the application usually fixes this.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("DB_SCHEMA_MISMATCH",1,"Your saved data is from a different version of PoseStudio. Please update the application to ensure compatibility.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("DB_LOCKED",4,"Another program or process is currently accessing your project data. Retrying connection...");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("DB_QUERY_FAILED",2,"An unexpected error occurred while saving or retrieving your data. If this persists, please let us know.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("APP_PLUGIN_MISSING",1,"Some required application components are missing. You may need to reinstall PoseStudio to fix this.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("APP_OUT_OF_MEMORY",1,"Your computer has run out of memory. Try closing other programs to free up system resources.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("APP_THREAD_CRASH",2,"A background process encountered an unexpected error. Your current workspace should be safe, but please save your progress.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("APP_INVALID_STATE",4,"That action cannot be performed right now. Please ensure your 3D rig or scene is properly set up and try again.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("NET_OFFLINE",3,"You are currently working offline. Cloud sync and community features are temporarily unavailable.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("NET_TIMEOUT",4,"The connection to the server timed out. Please check your internet connection and try again.");
INSERT INTO appErrors(appErrorCode,appErrorType,appErrorText) VALUES("NET_AUTH_FAILED",2,"Authentication failed. Please verify your login credentials to access the community hub.");
CREATE TABLE appErrorTypes(appErrorTypeId INTEGER PRIMARY KEY AUTOINCREMENT,appErrorTypeName TEXT NOT NULL,appErrorTypeStamp DATETIME DEFAULT CURRENT_TIMESTAMP);
INSERT INTO appErrorTypes(appErrorTypeName) VALUES("Critical");
INSERT INTO appErrorTypes(appErrorTypeName) VALUES("Error");
INSERT INTO appErrorTypes(appErrorTypeName) VALUES("Info");
INSERT INTO appErrorTypes(appErrorTypeName) VALUES("Warning");
CREATE TABLE appUsers(appUserID INTEGER PRIMARY KEY AUTOINCREMENT,appUserType INTEGER NOT NULL DEFAULT 0,appUserFullName TEXT NOT NULL DEFAULT "",appUserCompany TEXT NOT NULL DEFAULT "",appUserVendorName TEXT NOT NULL DEFAULT "",appUserEmail TEXT NOT NULL DEFAULT "",appUserPassword TEXT NOT NULL DEFAULT "",appUserCountry INTEGER NOT NULL DEFAULT 0,appUserTerms INTEGER NOT NULL DEFAULT 0,appUserLic INTEGER NOT NULL DEFAULT 0,appUserActive INTEGER NOT NULL DEFAULT 1,appUserStamp DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_appUserType ON appUsers(appUserType);
CREATE INDEX idx_appUserCountry ON appUsers(appUserCountry);
CREATE INDEX idx_appUserTerms ON appUsers(appUserTerms);
CREATE INDEX idx_appUserLic ON appUsers(appUserLic);
CREATE INDEX idx_appUserActive ON appUsers(appUserActive);
CREATE TABLE appUserTypes(appUserTypeId INTEGER PRIMARY KEY AUTOINCREMENT,appUserTypeName TEXT NOT NULL,appUserTypeStamp DATETIME DEFAULT CURRENT_TIMESTAMP);
INSERT INTO appUserTypes(appUserTypeName) VALUES("Individual");
INSERT INTO appUserTypes(appUserTypeName) VALUES("Business");
